### ISSUE TITLE
111.0 Breaks this component

### ISSUE THREAD

**Issue by Madseason41** [biern/hass-http_legacy_auth#1]
Updated to 111.0 and now I get the following error upon start.

Error during setup of component http_legacy_auth

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 190, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/http_legacy_auth/__init__.py", line 34, in async_setup
    hass.http.app.middlewares.append(auth_middleware);
  File "aiohttp\_frozenlist.pyx", line 97, in aiohttp._frozenlist.FrozenList.append
  File "aiohttp\_frozenlist.pyx", line 19, in aiohttp._frozenlist.FrozenList._check_frozen
RuntimeError: Cannot modify frozen list.

**Comment by Tho85** [comment]
I guess this has to do with the changed starting behavior of HA. The core now starts before all components are initialized. This means that the middleware stack is frozen before this component is loaded.

It looks like it isn't possible anymore to add middlewares in custom components.

**Comment by Madseason41** [comment]
Since node red already hast LLT access, I think I can use the http node to recreate a URL. Maybe I will have some luck going that route.
